services:
  app:
    container_name: jiosaavn-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=production
    restart: unless-stopped
